apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/opeomotayo/project.git
    targetRevision: HEAD
    path: charts/vault
    # plugin:
    #   name: argocd-vault-plugin-helm
    #   env:
    #     - name: RELEASE_NAME
    #       value: vault
    #     - name: NAMESPACE
    #       value: vault
    #     - name: VALUES_FILE
    #       value: vault-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true