apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: sonarqube
    meta.helm.sh/release-namespace: sonarqube
  labels:
    app: sonarqube
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release: sonarqube
  name: sonarqube-sonarqube
  namespace: sonarqube
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: http
    nodePort: 30003
  selector:
    app: sonarqube
    release: sonarqube
  type: NodePort
